### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by AceThePan** [Clowfoe/IMPOSTOR-UPDATE#11]
I wanted to compile it and this came up:
source/Main.hx:79: characters 61-65 : Float should be Int
source/Main.hx:79: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:79: characters 61-65 : ... For function argument 'child'
source/AmongStoryMenuState.hx:246: characters 24-27 : Static access to instance field add is not allowed
source/AmongStoryMenuState.hx:272: characters 25-28 : Static access to instance field add is not allowed
source/AmongStoryMenuState.hx:552: characters 24-27 : Static access to instance field add is not allowed
source/PlayState.hx:1463: characters 27-30 : Static access to instance field add is not allowed
source/PlayState.hx:3569: characters 4-18 : Warning : This case is unused
source/PlayState.hx:4329: characters 81-91 : Warning : This pattern is unused
source/ShopState.hx:325: characters 30-33 : Static access to instance field add is not allowed
source/AmongFreeplayState.hx:286: characters 24-27 : Static access to instance field add is not allowed

What do I need to do?

**Comment by SlickFromMars** [comment]
In order to better understand, are you building to windows or html5?

**Comment by Selever4Fun** [comment]
I'm on MacOS,

**Comment by Selever4Fun** [comment]
> In order to better understand, are you building to windows or html5?

I'm trying to build it on MacOS!

**Comment by RubenDatOneBoi3446** [comment]
check the psych git, i think they have the solution for some of it

**Comment by SlickFromMars** [comment]
Yeah that would probably be a better source, I've never really worked with Mac so this isn't my forte.

**Comment by Pixelgamer1286wastakenagain** [comment]
just downgrade the flixel to 4.11.0

haxelib set flixel 4.11.0

**Comment by Selever4Fun** [comment]
Well now I've got that:
Error: In file included from ./src/vlc/VlcBitmap.cpp:127:
/Users/NAME/Downloads/IMPOSTOR-UPDATE-main/source/vlc/cpp/src/LibVLC.cpp:4:10: warning: non-portable path to file '<stdint.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include <StdInt.h>
         ^~~~~~~~~~
         <stdint.h>
/Users/NAME/Downloads/IMPOSTOR-UPDATE-main/source/vlc/cpp/src/LibVLC.cpp:5:10: fatal error: 'windows.h' file not found
#include <windows.h> 
         ^~~~~~~~~~~

**Comment by Thecoolgamer6745** [comment]
I had this same problem but with linux. Idk what to do

**Comment by Plingvivin** [comment]
go to the command prompt and type these commands:
haxelib install flixel 4.11.0
haxelib set flixel 4.11.0
haxelib install flixel-addons 2.11.0
haxelib set flixel-addons 2.11.0

**Comment by FuroYT** [comment]
> I wanted to compile it and this came up: source/Main.hx:79: characters 61-65 : Float should be Int source/Main.hx:79: characters 61-65 : ... For optional function argument 'updateFramerate' source/Main.hx:79: characters 61-65 : ... For function argument 'child' source/AmongStoryMenuState.hx:246: characters 24-27 : Static access to instance field add is not allowed source/AmongStoryMenuState.hx:272: characters 25-28 : Static access to instance field add is not allowed source/AmongStoryMenuState.hx:552: characters 24-27 : Static access to instance field add is not allowed source/PlayState.hx:1463: characters 27-30 : Static access to instance field add is not allowed source/PlayState.hx:3569: characters 4-18 : Warning : This case is unused source/PlayState.hx:4329: characters 81-91 : Warning : This pattern is unused source/ShopState.hx:325: characters 30-33 : Static access to instance field add is not allowed source/AmongFreeplayState.hx:286: characters 24-27 : Static access to instance field add is not allowed
> 
> What do I need to do?

Flixel 5 is bad flixel 4 is the best

**Comment by MemeHovy** [comment]
> > I wanted to compile it and this came up: source/Main.hx:79: characters 61-65 : Float should be Int source/Main.hx:79: characters 61-65 : ... For optional function argument 'updateFramerate' source/Main.hx:79: characters 61-65 : ... For function argument 'child' source/AmongStoryMenuState.hx:246: characters 24-27 : Static access to instance field add is not allowed source/AmongStoryMenuState.hx:272: characters 25-28 : Static access to instance field add is not allowed source/AmongStoryMenuState.hx:552: characters 24-27 : Static access to instance field add is not allowed source/PlayState.hx:1463: characters 27-30 : Static access to instance field add is not allowed source/PlayState.hx:3569: characters 4-18 : Warning : This case is unused source/PlayState.hx:4329: characters 81-91 : Warning : This pattern is unused source/ShopState.hx:325: characters 30-33 : Static access to instance field add is not allowed source/AmongFreeplayState.hx:286: characters 24-27 : Static access to instance field add is not allowed
> > What do I need to do?
> 
> Flixel 5 is bad flixel 4 is the best

no shit

**Comment by MemeHovy** [comment]
but flixel 5 is good in some cases
