### ISSUE TITLE
Error while Compiling (Windows)

### ISSUE THREAD

**Issue by Pixelgamer1286wastakenagain** [Clowfoe/IMPOSTOR-UPDATE#15]
i trying compile the old builds and there is a error:
source/Main.hx:76: characters 61-65 : Float should be Int
source/Main.hx:76: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:76: characters 61-65 : ... For function argument 'child'
source/AmongFreeplayState.hx:237: characters 30-33 : Static access to instance field add is not allowed

What do I need to do?

**Comment by RubenDatOneBoi3446** [comment]
go to the psych engine git, they might have the solution

**Comment by RubenDatOneBoi3446** [comment]
well for some i hope

**Comment by Pixelgamer1286wastakenagain** [comment]
nope

**Comment by Pixelgamer1286wastakenagain** [comment]
still have same error

**Comment by Pixelgamer1286wastakenagain** [comment]
i got it
just downgrade the flixel to 4.11.0

**Comment by RubenDatOneBoi3446** [comment]
yah the way i fixed it was i just replaced a line of code with another
