### ISSUE TITLE
Song volume isn't consistent

### ISSUE THREAD

**Issue by biomseed** [Clowfoe/IMPOSTOR-UPDATE#27]
The volume of some songs aren't consistent with the others, some are too quiet (take sussus moogus and compare it with danger and you'll see what I mean). The volume of some songs' vocals are also inconsistent with the volume of the instrumental (Boiling point).

**Comment by MemeHoovy** [comment]
that's how the songs were exported

**Comment by biomseed** [comment]
> that's how the songs were exported

i think the issue is fixed now
