### ISSUE TITLE
Error when compiling on linux

### ISSUE THREAD

**Issue by Thecoolgamer6745** [Clowfoe/IMPOSTOR-UPDATE#29]
When i try to compile on linux i get this error:

source/MainMenuState.hx:83: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:83: characters 73-74 : For optional function argument 'repeatAxes'
source/MainMenuState.hx:89: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:89: characters 73-74 : For optional function argument 'repeatAxes'
source/OptionsState.hx:48: characters 73-74 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:48: characters 73-74 : For optional function argument 'repeatAxes'
source/OptionsState.hx:55: characters 79-80 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:55: characters 79-80 : For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:146: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:146: characters 73-74 : For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:153: characters 79-80 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:153: characters 79-80 : For optional function argument 'repeatAxes'
source/PlayState.hx:795: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:795: characters 71-72 : For optional function argument 'repeatAxes'
source/PlayState.hx:802: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:802: characters 71-72 : For optional function argument 'repeatAxes'
source/PlayState.hx:809: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:809: characters 71-72 : For optional function argument 'repeatAxes'
source/PlayState.hx:816: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:816: characters 71-72 : For optional function argument 'repeatAxes'
source/PlayState.hx:823: characters 74-75 : Int should be flixel.util.FlxAxes
source/PlayState.hx:823: characters 74-75 : For optional function argument 'repeatAxes'
source/PlayState.hx:991: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:991: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:998: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:998: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:1005: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1005: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:1012: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1012: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:1019: characters 84-85 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1019: characters 84-85 : For optional function argument 'repeatAxes'
source/PlayState.hx:1352: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1352: characters 75-76 : For optional function argument 'repeatAxes'
source/PlayState.hx:1360: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1360: characters 75-76 : For optional function argument 'repeatAxes'
source/PlayState.hx:1724: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1724: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:3444: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:3444: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:3569: characters 4-18 : Warning : This case is unused
source/PlayState.hx:4329: characters 81-91 : Warning : This pattern is unused
source/AmongFreeplayState.hx:142: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:142: characters 73-74 : For optional function argument 'repeatAxes'
source/AmongFreeplayState.hx:149: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:149: characters 73-74 : For optional function argument 'repeatAxes'
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y
/home/christianpanta34/haxelib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
source/TitleState.hx:181: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:181: characters 73-74 : For optional function argument 'repeatAxes'
source/TitleState.hx:187: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:187: characters 73-74 : For optional function argument 'repeatAxes'

**Comment by MaysLastPlayGithub** [comment]
You should use flixel-addons 2.11.0

**Comment by Thecoolgamer6745** [comment]
> You should use flixel-addons 2.11.0

What command do i type?
