### ISSUE TITLE
many many many compiling errors

### ISSUE THREAD

**Issue by SlickFromMars** [Clowfoe/IMPOSTOR-UPDATE#69]
getting a crap load of errors when compiling to windows, I'm assuming I'm using different haxelib versions so I'm gonna try to update the code if possible.

source/AmongStoryMenuState.hx:145: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:145: characters 73-74 : ... For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:152: characters 79-80 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:152: characters 79-80 : ... For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:246: characters 24-27 : Static access to instance field add is not allowed
source/AmongStoryMenuState.hx:272: characters 25-28 : Static access to instance field add is not allowed
source/AmongStoryMenuState.hx:552: characters 24-27 : Static access to instance field add is not allowed
source/MainMenuState.hx:83: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:83: characters 73-74 : ... For optional function argument 'repeatAxes'
source/MainMenuState.hx:89: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:89: characters 73-74 : ... For optional function argument 'repeatAxes'
source/OptionsState.hx:48: characters 73-74 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:48: characters 73-74 : ... For optional function argument 'repeatAxes'
source/OptionsState.hx:55: characters 79-80 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:55: characters 79-80 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:802: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:802: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:809: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:809: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:816: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:816: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:823: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:823: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:830: characters 74-75 : Int should be flixel.util.FlxAxes
source/PlayState.hx:830: characters 74-75 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:998: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:998: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1005: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1005: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1012: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1012: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1019: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1019: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1026: characters 84-85 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1026: characters 84-85 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1359: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1359: characters 75-76 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1367: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1367: characters 75-76 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1472: characters 27-30 : Static access to instance field add is not allowed
source/PlayState.hx:1733: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1733: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:3462: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:3462: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:3587: characters 4-18 : Warning : This case is unused
source/PlayState.hx:4354: characters 81-91 : Warning : This pattern is unused
source/ShopState.hx:325: characters 30-33 : Static access to instance field add is not allowed
source/AmongFreeplayState.hx:142: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:142: characters 73-74 : ... For optional function argument 'repeatAxes'
source/AmongFreeplayState.hx:149: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:149: characters 73-74 : ... For optional function argument 'repeatAxes'
source/AmongFreeplayState.hx:286: characters 24-27 : Static access to instance field add is not allowed
source/TitleState.hx:187: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:187: characters 73-74 : ... For optional function argument 'repeatAxes'
source/TitleState.hx:193: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:193: characters 73-74 : ... For optional function argument 'repeatAxes'
PS C:\Users\minec\Documents\GitHub\IMPOSTOR-UPDATE> lime test windows
source/AmongStoryMenuState.hx:145: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:145: characters 73-74 : ... For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:152: characters 79-80 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:152: characters 79-80 : ... For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:246: characters 24-27 : Static access to instance field add is not allowed
source/AmongStoryMenuState.hx:272: characters 25-28 : Static access to instance field add is not allowed
source/AmongStoryMenuState.hx:552: characters 24-27 : Static access to instance field add is not allowed
source/MainMenuState.hx:83: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:83: characters 73-74 : ... For optional function argument 'repeatAxes'
source/MainMenuState.hx:89: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:89: characters 73-74 : ... For optional function argument 'repeatAxes'
source/OptionsState.hx:48: characters 73-74 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:48: characters 73-74 : ... For optional function argument 'repeatAxes'
source/OptionsState.hx:55: characters 79-80 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:55: characters 79-80 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:802: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:802: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:809: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:809: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:816: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:816: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:823: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:823: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:830: characters 74-75 : Int should be flixel.util.FlxAxes
source/PlayState.hx:830: characters 74-75 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:998: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:998: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1005: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1005: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1012: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1012: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1019: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1019: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1026: characters 84-85 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1026: characters 84-85 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1359: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1359: characters 75-76 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1367: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1367: characters 75-76 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1472: characters 27-30 : Static access to instance field add is not allowed
source/PlayState.hx:1733: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1733: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:3462: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:3462: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:3587: characters 4-18 : Warning : This case is unused
source/PlayState.hx:4354: characters 81-91 : Warning : This pattern is unused
source/ShopState.hx:325: characters 30-33 : Static access to instance field add is not allowed
source/AmongFreeplayState.hx:142: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:142: characters 73-74 : ... For optional function argument 'repeatAxes'
source/AmongFreeplayState.hx:149: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:149: characters 73-74 : ... For optional function argument 'repeatAxes'
source/AmongFreeplayState.hx:286: characters 24-27 : Static access to instance field add is not allowed
source/TitleState.hx:187: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:187: characters 73-74 : ... For optional function argument 'repeatAxes'
source/TitleState.hx:193: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:193: characters 73-74 : ... For optional function argument 'repeatAxes'

**Comment by SlickFromMars** [comment]
nevermind I fixed them :) making a pr

**Comment by LolMan1022** [comment]
how did you fix it?? im having this exact issue

**Comment by SlickFromMars** [comment]
I ran a `haxelib update` command and then updated the code
heres my fork [https://github.com/SlickFromMars/IMPOSTOR-UPDATE](url)
copy from here if you want
