### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by Thecoolgamer6745** [Clowfoe/IMPOSTOR-UPDATE#7]
Do i need to install any plugins to compile this?
It keeps saying this when i do lime build windows
Process creation failure : cl.exe

**Comment by MelonMCOfficial** [comment]
did you google the error first

**Comment by Thecoolgamer6745** [comment]
> did you google the error first

Yes. I coudnt really find anything

**Comment by biomseed** [comment]
reinstall visual studio
