### ISSUE TITLE
trouble compiling :(

### ISSUE THREAD

**Issue by chilleryzz** [Clowfoe/IMPOSTOR-UPDATE#79]
i've tried installing multiple versions of things, and i get this:

source/PlayState.hx:3052: characters 4-18 : Warning : This case is unused
source/PlayState.hx:3763: characters 10-33 : Warning : This pattern is unused
source/Achievements.hx:146: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/AmongFreeplayState.hx:102: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/AmongStoryMenuState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:593: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/ShopState.hx:193: characters 9-45 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/ShopState.hx:732: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:95: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/HenryState.hx:290: characters 17-31 : Warning : Local variable finishCallback might be used before being initialized
C:\Users\censored\Downloads\IMPOSTOR-UPDATE-71b90fd3e7eda7df0dae29e43232a5a1202cbb69\IMPOSTOR-UPDATE-71b90fd3e7eda7df0dae29e43232a5a1202cbb69\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
PS C:\Users\censored\Downloads\IMPOSTOR-UPDATE-71b90fd3e7eda7df0dae29e43232a5a1202cbb69\IMPOSTOR-UPDATE-71b90fd3e7eda7df0dae29e43232a5a1202cbb69>

please help

**Comment by chilleryzz** [comment]
also it's for windows!!

**Comment by BombasticTom** [comment]
did you modify anything

**Comment by chilleryzz** [comment]
- [x] no but i fixed it yippe

**Comment by LolMan1022** [comment]
how did you fix it??

**Comment by chilleryzz** [comment]
installed visual studio
