### ISSUE TITLE
Help compiling

### ISSUE THREAD

**Issue by LongNoseDog** [Clowfoe/IMPOSTOR-UPDATE#8]
When attempting to compile I receive the following message

source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : For optional function argument 'updateFramerate'
source/AmongStoryMenuState.hx:145: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:145: characters 73-74 : For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:152: characters 79-80 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:152: characters 79-80 : For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:246: characters 24-27 : Class<flixel.input.mouse.FlxMouseEventManager> has no field add
source/AmongStoryMenuState.hx:272: characters 25-28 : Class<flixel.input.mouse.FlxMouseEventManager> has no field add
source/AmongStoryMenuState.hx:552: characters 24-27 : Class<flixel.input.mouse.FlxMouseEventManager> has no field add
source/MainMenuState.hx:83: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:83: characters 73-74 : For optional function argument 'repeatAxes'
source/MainMenuState.hx:89: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:89: characters 73-74 : For optional function argument 'repeatAxes'
source/OptionsState.hx:48: characters 73-74 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:48: characters 73-74 : For optional function argument 'repeatAxes'
source/OptionsState.hx:55: characters 79-80 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:55: characters 79-80 : For optional function argument 'repeatAxes'
source/PlayState.hx:795: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:795: characters 71-72 : For optional function argument 'repeatAxes'
source/PlayState.hx:802: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:802: characters 71-72 : For optional function argument 'repeatAxes'
source/PlayState.hx:809: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:809: characters 71-72 : For optional function argument 'repeatAxes'
source/PlayState.hx:816: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:816: characters 71-72 : For optional function argument 'repeatAxes'
source/PlayState.hx:823: characters 74-75 : Int should be flixel.util.FlxAxes
source/PlayState.hx:823: characters 74-75 : For optional function argument 'repeatAxes'
source/PlayState.hx:991: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:991: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:998: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:998: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:1005: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1005: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:1012: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1012: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:1019: characters 84-85 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1019: characters 84-85 : For optional function argument 'repeatAxes'
source/PlayState.hx:1352: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1352: characters 75-76 : For optional function argument 'repeatAxes'
source/PlayState.hx:1360: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1360: characters 75-76 : For optional function argument 'repeatAxes'
source/PlayState.hx:1463: characters 27-30 : Class<flixel.input.mouse.FlxMouseEventManager> has no field add
source/PlayState.hx:1724: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1724: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:3444: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:3444: characters 81-82 : For optional function argument 'repeatAxes'
source/PlayState.hx:3569: characters 4-18 : Warning : This case is unused
source/PlayState.hx:4329: characters 81-91 : Warning : This pattern is unused
source/ShopState.hx:325: characters 30-33 : Class<flixel.input.mouse.FlxMouseEventManager> has no field add
source/AmongFreeplayState.hx:142: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:142: characters 73-74 : For optional function argument 'repeatAxes'
source/AmongFreeplayState.hx:149: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:149: characters 73-74 : For optional function argument 'repeatAxes'
source/AmongFreeplayState.hx:286: characters 24-27 : Class<flixel.input.mouse.FlxMouseEventManager> has no field add
source/TitleState.hx:181: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:181: characters 73-74 : For optional function argument 'repeatAxes'
source/TitleState.hx:187: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:187: characters 73-74 : For optional function argument 'repeatAxes'

**Comment by Thecoolgamer6745** [comment]
Thats weird

**Comment by MaysLastPlayGithub** [comment]
U need to use flixel-addons 2.11.0

**Comment by LongNoseDog** [comment]
It works now. Thank you.

**Comment by AndromedaIvet** [comment]
Hey, i get this again, even when i install that addons
source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:78: characters 61-65 : ... For function argument 'child'
source/FreeplayState.hx:108: characters 50-51 : Int should be flixel.util.FlxAxes
source/FreeplayState.hx:108: characters 50-51 : ... For optional function argument 'repeatAxes'
source/StoryMenuState.hx:64: characters 56-57 : Int should be flixel.util.FlxAxes
source/StoryMenuState.hx:64: characters 56-57 : ... For optional function argument 'repeatAxes'
source/MainMenuState.hx:93: characters 78-79 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:93: characters 78-79 : ... For optional function argument 'repeatAxes'
source/MainMenuState.hx:100: characters 83-84 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:100: characters 83-84 : ... For optional function argument 'repeatAxes'
source/EXMusicMenuState.hx:83: characters 78-79 : Int should be flixel.util.FlxAxes
source/EXMusicMenuState.hx:83: characters 78-79 : ... For optional function argument 'repeatAxes'
source/EXMusicMenuState.hx:90: characters 83-84 : Int should be flixel.util.FlxAxes
source/EXMusicMenuState.hx:90: characters 83-84 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:434: characters 77-78 : Int should be flixel.util.FlxAxes
source/PlayState.hx:434: characters 77-78 : ... For optional function argument 'repeatAxes'
source/TitleState.hx:370: characters 64-65 : Int should be flixel.util.FlxAxes
source/TitleState.hx:370: characters 64-65 : ... For optional function argument 'repeatAxes'

**Comment by MemeHovy** [comment]
use flixel 4.11.0 and flixel addons 2.11.0
