### ISSUE TITLE
Teensy bit of trouble compiling

### ISSUE THREAD

**Issue by NBowl** [Clowfoe/IMPOSTOR-UPDATE#84]
source/Main.hx:5: characters 8-17 : You cannot access the cpp package while targeting js (for cpp.vm.Gc)
export/release/html5/haxe/ApplicationMain.hx:319: characters 48-52 : ... referenced here

I genuinely have NO clue how to change the target from js to cpp. Whatever I try to do only results in more errors

**Comment by windows10win7posreadywoeskio** [comment]
your building in HTML5 **you fucking sore loser.**

download VS Community 2019 with workload **game development**

**_and build in Windows._**

**Comment by NBowl** [comment]
Thank you for the response , however harsh it may have been , but i have since learned that i'm an actual dumbass and that there's a build bat in the art folder and it just builds. beautifully may i add . thank u anyway 4 pointing me in the right direction
