### ISSUE TITLE
apparently airship bf skin is a gf skin

### ISSUE THREAD

**Issue by JustJasonLol** [Clowfoe/IMPOSTOR-UPDATE#9]
just saw uniquegeese's stream and he discovered that airship bf skin is a gf one lol

**Comment by LongNoseDog** [comment]
Yeah

**Comment by SlickFromMars** [comment]
Yeah I ran into that issue during my playthrough as well. I'm trying to find a solution to that so I can make a pull request and hopefully have it fixed. I really don't think that it's intentional.

**Comment by SlickFromMars** [comment]
Oops nevermind they already fixed it lol

**Comment by JustJasonLol** [comment]
closing this since they listened to it and fixed it
